In [2]:
import pandas as pd 
df = pd.read_csv('spam_master.csv')
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.groupby('Category').describe()

Message                                    
           count unique                     top freq
Category                                            
              0      0                     NaN  NaN
ham         8495   8045  Sorry, I'll call later   30
spam        2241   2091                      \n   16

In [4]:
df['spam_ham'] = df['Category'].apply(lambda x:1 if x == 'spam' else 0)
df.head()

Category                                            Message  spam_ham
0      ham  Go until jurong point, crazy.. Available only ...         0
1      ham                      Ok lar... Joking wif u oni...         0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...         1
3      ham  U dun say so early hor... U c already then say...         0
4      ham  Nah I don't think he goes to usf, he lives aro...         0

In [5]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(df['Message'], df['spam_ham'], test_size = 0.25)

In [6]:
if df['Message'].isnull().values.any() == True:                  #dropping np.nan values
   h =1 
df = df.dropna()

In [7]:
from sklearn.feature_extraction.text import CountVectorizer

a = CountVectorizer()

x_train_count = a.fit_transform(x_train.values.astype('U'))

In [8]:
df.isnull().values.any()

False

In [9]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()

model.fit(x_train_count, y_train)

MultinomialNB()

In [10]:
text = [
    'Hi Samuel, When’s the last time you finished everything on your daily to-do list? If you’re like most busy executives, you’re constantly struggling to stay on top of everything – let alone be the effective leader you need to be. Our software helps motivated entrepreneurs like Gary Vaynerchuk, Tim Ferriss, and Malcolm Gladwell save as much as ten hours per week that can be directed back at your top priorities. I’d love to give you a personalized demo. When are you free next week?'
]

text_count = a.transform(text)
text_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [19]:
# predicting the class of 'text'  where spam is equivalent to zero and one is equivalent to ham
model.predict(text_count)[0]

array([0], dtype=int64)

In [13]:
# Predicting the probabilities for input text begin spam and ham
p = model.predict_proba(text_count)[0]
p

array([9.99971989e-01, 2.80112446e-05])

In [22]:
print('Probability of being a Ham: ', p[0])
print('Probability of being a Spam: ', p[1])

Probability of being a Ham:  0.9999719887554083
Probability of being a Spam:  2.8011244642354006e-05
